name:                data-combinator
version:             0.1.0.0
synopsis:            Combinator of raw data
description:         Please see README.md
homepage:            https://github.com/theam/body-sensorial-project
license:             Apache-2.0
author:              Theam
maintainer:          nick@theam.io
copyright:           2017 The Agile Monkeys S.L.
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - analyze
  - foundation
  - optparse-simple
  - vector
  - transformers >= 0.5.2 && < 0.6
  - either >= 4.4 && < 5
  - text
  - exceptions
  - bytestring
  - process
  - inline-r

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings

executables:
  data-combinator:
    source-dirs:      src
    main:             Main.hs
