resolver: lts-9.0

packages:
- location: '.'
- extra-dep: true
  location:
    git: 'https://github.com/NickSeagull/analyze.git'
    commit: '6f423a125a780866d10029accebe422acf6f112f'

extra-deps: []

flags: {}

extra-package-dbs: []