#!/bin/bash

# Install XCode cli tools
xcode-select --install

# Install R and necessary packages
if hash R 2>/dev/null; then
    echo "R is installed, skipping installation"
else
    brew tap homebrew/science && \
    brew install Caskroom/cask/xquartz && \
    brew install r
fi
R -e "install.packages('data.table', repos='http://cran.rstudio.com/')" && \
R -e "install.packages('zoo', repos='http://cran.rstudio.com/')"

# Install necessary programs
brew install ffmpeg && \
brew install sox && \
brew install curl && \
brew install pkg-config && \
curl -sSL https://get.haskellstack.org/ | sh

# Setup project
stack setup && \
cd data-combinator && \
stack build && \
cd ../visualizer-server && \
stack build && \
cd ../data-combinator && \
stack exec data-combinator -- all && \
cd ../visualizer-server && \
stack exec visualizer-server
