name:                visualizer-server
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/theam/visualizer-server#readme
license:             BSD3
author:              Theam
maintainer:          nick@theam.io
copyright:           2017 Theam
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - servant
  - servant-server
  - aeson
  - wai
  - wai-cors
  - warp
  - analyze
  - vector
  - text
  - array
  - dsp

executables:
  visualizer-server:
    source-dirs:      src
    main:             Main.hs
