name:                visualizer-client
version:             0.1.0.0
synopsis:            Client for the visualizer server
description:         Please see README.md
homepage:            https://github.com/theam/visualizer-client#readme
license:             Apache-2.0
author:              Theam
maintainer:          nick@theam.io
copyright:           2017 Theam
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - miso >= 0.6 && < 1.0

default-extensions:
- OverloadedStrings

executables:
  visualizer-client:
    source-dirs:      src
    main:             Main.hs
