
name:                segmentation
version:             0.1.0.0
homepage:            https://github.com/theam/segmentation#readme
license:             BSD3
author:              Theam
maintainer:          nick@theam.io
copyright:           2017 Theam
category:            DataScience
extra-source-files:
- README.md

default-extensions:
  - OverloadedStrings
  - TemplateHaskell
  - ExtendedDefaultRules

dependencies:
  - base >= 4.6 && < 5
  - array
  - dsp
  - storablevector
  - hsndfile
  - hsndfile-storablevector
  - text
  - pyfi


executables:
  run-test:
    source-dirs:      src
    main:             Main.hs
